site_name: 上海地铁Wiki
theme:
  name: material
  language: zh
  logo: logo.png
  features:
  - navigation.top
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
copyright: 本wiki暂未编写完毕，数据不完全，且本wiki与上海申通地铁集团有限公司并无关系。
repo_url: https://github.com/BSOD-qian/shmetrowiki
repo_name: BSOD-qian/shmetrowiki